name: CI for Java + Docker App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker image
        run: docker build -t sem-app .

      - name: Run Docker container
        run: docker run --name sem-container -d sem-app

      - name: Show container logs
        run: docker logs sem-container
